<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>plist</string>
      <string>tmLanguage</string>
      <string>tmTheme</string>
      <string>tmSnippet</string>
      <string>tmPreferences</string>
    </array>
    <key>firstLineMatch</key><string>^&lt;\?xml </string>
    <key>foldingStartMarker</key><string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
    <key>foldingStopMarker</key><string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
    <key>keyEquivalent</key><string>^~p</string>
    <key>name</key><string>PropertyList</string>
    <key>scopeName</key><string>text.plist</string>
    <key>uuid</key><string>1CC093AD-1628-4433-909E-6B92B592C683</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key><string>key</string>
        <key>match</key><string><![CDATA[<(key)>(.+)</(key)>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>variable.other.plist</string></dict>
          <key>2</key>
          <dict><key>name</key><string>variable.other.plist</string></dict>
          <key>3</key>
          <dict><key>name</key><string>variable.other.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>string</string>
        <key>begin</key><string><![CDATA[<(string)>]]></string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>end</key><string><![CDATA[</(string)>]]></string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict><key>include</key><string>source.oniregexp</string></dict>
          <dict><key>include</key><string>#cdata</string></dict>
          <dict>
            <key>match</key><string><![CDATA[<|>|(&(?!(gt|lt|amp|apos|quot);))]]></string>
            <key>name</key><string>invalid.string.plist</string>
          </dict>
          <dict>
            <key>match</key><string><![CDATA[([^<>&]|(&(gt|lt|amp|apos|quot);))+]]></string>
            <key>name</key><string>constant.string.plist</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key><string>bool</string>
        <key>match</key><string><![CDATA[<(true|false)/>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>integer</string>
        <key>match</key><string><![CDATA[<(integer)>(0|[1-9][0-9]*)</(integer)>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
          <key>2</key>
          <dict><key>name</key><string>constant.integer.plist</string></dict>
          <key>3</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>real</string>
        <key>match</key><string><![CDATA[<(real)>([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)</(real)>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
          <key>2</key>
          <dict><key>name</key><string>constant.real.plist</string></dict>
          <key>4</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>date</string>
        <key>match</key><string><![CDATA[<(date)>(\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ)</(date)>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
          <key>2</key>
          <dict><key>name</key><string>constant.date.plist</string></dict>
          <key>3</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>data</string>
        <key>match</key><string><![CDATA[<(data)>([a-zA-Z0-9+/=]+)</(data)>]]></string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
          <key>2</key>
          <dict><key>name</key><string>constant.data.plist</string></dict>
          <key>3</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key><string>array</string>
        <key>begin</key><string><![CDATA[<(array)>]]></string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>end</key><string><![CDATA[</(array)>]]></string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict><key>include</key><string>text.plist</string></dict>
        </array>
      </dict>
      <dict>
        <key>comment</key><string>dict</string>
        <key>begin</key><string><![CDATA[<(dict)>]]></string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>end</key><string><![CDATA[</(dict)>]]></string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict><key>name</key><string>storage.type.plist</string></dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict><key>include</key><string>text.plist</string></dict>
        </array>
      </dict>
      <dict><key>include</key><string>text.xml</string></dict>
    </array>
    <key>repository</key>
    <dict>
      <key>cdata</key>
      <dict>
        <key>begin</key><string>&lt;!\[CDATA\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict><key>name</key><string>punctuation.definition.string.begin.plist</string></dict>
        </dict>
        <key>end</key><string>]]&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict><key>name</key><string>punctuation.definition.string.end.plist</string></dict>
        </dict>
        <key>name</key><string>string.unquoted.cdata.plist</string>
      </dict>
    </dict>
  </dict>
</plist>
