<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt.ch</string>
		<string>txt.ol</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\{</string>
	<key>foldingStopMarker</key>
	<string>^\}</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Novel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.prose.definition.key</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.prose.definition.value</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((?:\b\s?\w+\b)+)\s{3,}([\w]+)(?:\t|\s){2,}[^\n]+</string>
			<key>name</key>
			<string>string.prose.definition</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.prose.dialogue.speaker</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((?:\b\s?\w+\b)+)\s{3,}[^\n]+</string>
			<key>name</key>
			<string>string.prose.dialogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\([^\)]*\)</string>
			<key>name</key>
			<string>comment.prose</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.{3,}</string>
			<key>name</key>
			<string>comment.prose.break</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\{#.*$</string>
			<key>name</key>
			<string>comment.prose.section.start</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\}$</string>
			<key>name</key>
			<string>comment.prose.section.end</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.prose.novel</string>
	<key>uuid</key>
	<string>8A0ECE42-5425-415A-A254-98FFDE881289</string>
</dict>
</plist>
